Error out on PRs coming from forks

diff --git a/.github/workflows/check-teams.yml b/.github/workflows/check-teams.yml
--- a/.github/workflows/check-teams.yml
+++ b/.github/workflows/check-teams.yml
@@ -16,6 +16,11 @@ jobs:
   check:
     runs-on: ubuntu-latest
     steps:
+      - name: Check PR comes from branch
+        if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository
+        run: |
+          echo "::error::Pull Requests from forks are not allowed. Please submit your PR from a branch. If you don't have permissions, check with a member of @conda/infrastructure."
+          exit 1
       - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
         with:
           persist-credentials: false
